name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error log"
      - run: echo "::warning::This is a warning log"
      - run: echo "::notice::This is a notice log"
      - run: echo "::debug::This is a debug log"
      - run: echo "::info::This is an info log"