name: Job Summary
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- firest list" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second list" >> "${GITHUB_STEP_SUMMARY}"